<a href="https://colab.research.google.com/github/syedhammadahmed/quantumcomputings20/blob/master/hw_1/hw_1_problem_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## HW 1 ##

### Problem 2 ###

**Some definitions**

Let 

$$M\in\mathbb{R}^{n\times n}$$ be an arbitrary matrix.  

Let $$p(x)=a_0 + a_1 x + a_2 x^2 + \ldots + a_n x^n \in\mathbb{R}[x]$$ be an arbitrary polynomial of less or equal to $n$.

The above polynomial can be used to define a matrix function that takes matrices as input and outputs matrices as follows: 

$$p(M) = a_0 I + a_1 M + \ldots + a_n M^n,$$ 

that is, each monomial $x^k$ is substituted by the corresponding matrix power $M^k$.

We say that a polynomial $p(x)$ annihilates a matrix $M\in\mathbb{R}^{n\times n}$ iff $p(M)=\boldsymbol{0}$, where $\boldsymbol{0}$ is the zero matrix.

**Task**

The task is to write a function ```annihilate_poly``` that takes as input an arbitrary square numpy array $M$ and outputs a vector whose cofficients are the coefficients of a (non-trivial) polynomial that annihilates $M$.  One-trivial means that its is not the zero polynomial which maps every matrix to the zero matrix.

In [43]:
import numpy as np
import numpy.linalg as NPLA
import scipy.linalg as SPLA

#references: 
#[1] https://www.answiz.com/questions/54241/python-numpy-scipy-finding-the-null-space-of-a-matrix


def vec(m):
  n = np.shape(m)[0]
  m = np.array(m)
  m = np.reshape(m, (n * n, 1))
  return m

def mPowerK(m, k):
  return NPLA.matrix_power(m, k)

def makePolynomial(m, k):
  n, n = np.shape(m)
  polynomial = np.array([])
  # for i in range(k + 1):
  for i in range(0, k + 1):
    monomial = mPowerK(m, i)
    print(monomial)
    vectorizedMonomial = vec(monomial)
    polynomial = np.concatenate(polynomial, vectorizedMonomial)
    polynomial = np.reshape(polynomial, (n * n, i + 1))
  print(polynomial)
  print(np.shape(polynomial))
  return polynomial

# def mPowerK(m, k):
#   m = vec(m)
#   p = np.array([])
#   for i in range(n * n + 1):
#     p = np.append(p, m)
#   p = np.reshape(p, (n * n, n * n + 1))  
#   print(p)
#   return p

def annihilate_poly(m, k):
  n, n = np.shape(m)
  polynomial = makePolynomial(m, k)
  # eigenValue = NPLA.eig(polynomial)
  # nullSpace = SPLA.null_space(polynomial - eigenValue[0][0]*np.eye(n), rcond=1e-14)
  nullSpace = SPLA.null_space(polynomial)
  # nullSpace = nullSpace.T.dot(nullSpace) 
  return nullSpace
  # mPowerK(m, k)

def main():
  n = 3
  k = 3
  m = np.array([[1, -1, -1],
               [1, -2, 1],
               [0, 1, -3]])
  m = np.reshape(m, (n, n))
  coeffs = annihilate_poly(m, k)
  print(coeffs)

if __name__ == "__main__":
    main()



[[1 0 0]
 [0 1 0]
 [0 0 1]]


TypeError: ignored

**Hint**

You can reduce the problem to finding a linear dependance relationship between the $n+1$ vectors 

$$\mathrm{vec}(I), \mathrm{vec}(M), \mathrm{vec}(M^2),\ldots,\mathrm{vec}(M^n)\in\mathrm{R}^{n^2}.$$



The operation $\mathrm{vec}$ turns a square matrix $M\in\mathbb{R}^{n\times n}$ into a vector $v\in\mathbb{R}^{n^2}$ by first listing the entries of the first row, then those of the second row etc.

Update: 

To solve this problem, you have to compute the null space of the matrix $A\in \mathbb{R}^{n^2\times (n+1)}$ whose columns are the vectors $\mathrm{vec}(M^k)$ for $k\in\{0,\ldots,n\}$.


(This is not needed: 

If you don't remeber how to compute the find a linear dependance relationship, check out this stackoverflow post: https://math.stackexchange.com/questions/2198960/finding-linear-dependence-relation

You can use https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.solve.html to solve the resulting matrix equation.)

**Task**

Write a function ```annihilate_min_deg_poly``` that computes a non-trivial polynomial that annihilates a given square matrix and has the smallest possible degree.  Recall that a polynomial $p(x)$ has degree $d$ if the coefficient $a_{d+1}=\ldots=a_n=0$.

In [4]:
print("Task 2: ")

Task 2: 
